- src/shared/actions/api.js
- src/shared/containers/app.jsx
- src/shared/reducers/app.js
- src/shared/sagas/api.js
- src/shared/sagas/auth.js
- tests/shared/reducers/app.test.js
This PR adds tests and new action creators.
> Add some tests for the app reducer

- .eslintrc.json
- package.json
- tests/shared/components/displayWebServiceEditor.test.js
- tests/shared/components/fileInput.test.js
- tests/shared/components/loading.test.js
- tests/shared/reducers/app.test.js
- tests/shared/reducers/auth.test.js
- tests/shared/reducers/createReducer.test.js
- tests/shared/reducers/index.test.js
- tests/shared/reducers/initialize.test.js
- tests/shared/reducers/user.test.js
- webpack.common.js
tests code wasn’t correctly formatted.
> Lint tests

- .codacy.yaml
- package.json
- src/client/index.js
- src/public/css/app.css
- src/shared/containers/app.jsx
> add app css

- src/shared/reducers/message.js
- src/shared/sagas/auth.js
- tests/shared/reducers/message.test.js
> avoid blank screen on failed signin

- src/shared/containers/adminManager.jsx
- src/shared/containers/processingDialog.jsx
- src/shared/containers/screen.jsx
- src/shared/containers/signInDialog.jsx
- tests/shared/containers/__snapshots__/signInDialog.test.js.snap
- tests/shared/containers/processingDialog.test.jsx
- tests/shared/containers/signInDialog.test.js
Make Zoapp-front React 16.3.0 lifecycle compliant and close #54.
fix Opla/front#120
> Use react 16.3 lifecycle functions

- src/shared/containers/app.jsx
Allow to use a drawer footer
---
Need zoapp/ui#20 update
> Refactor drawer

- src/shared/containers/app.jsx
I can't remove the `Toolbar` component, if I do that I don't know how to fully display the `Content`. I think the `Content` componen itself is not made to be render without a toolbar.
> display toolbar in screen configuration

- src/shared/front.jsx
Fix a relative import issue impacting children projects.
> Fix relative import

- src/client/index.js
- src/public/css/app.css
- src/shared/containers/app.jsx
Add Dark theme to Drawer and White theme to Toolbar.
> Drawer Dark theme. Toolbar White theme.

- src/client/index.js
- src/shared/containers/app.jsx
Close temporary drawer on item click
> Close temporary drawer

- package.json
- src/client/index.js
- src/public/css/app.css
- src/shared/containers/app.jsx
- yarn.lock
- bigger user icon
- parameters color and backgroundcolor to change Button appearance
> Enhance toolbar buttons and icons

- package.json
- src/shared/containers/admin/advanced.jsx
Populates the public url field. Makes it disabled for now.
> fix public url field

- package.json
- src/shared/services.js
see https://github.com/Zoapp/common/pull/11
TODO
> [WIP] make api url optional

- .travis.yml
- package.json
> npm snapshots.

- package.json
- src/shared/services.js
> Revert "make api url optional"

- .travis.yml
- package.json
Simplifies the publish process. Enables us to use yarn workspaces and yarn link in a simple way.
> Enables yarn workspaces

- package.json
- src/shared/components/auth/signUp.jsx
- src/shared/containers/authenticate.jsx
- tests/shared/components/signUp.test.js
- yarn.lock
Add signUp policy agreement with configuration variable policyUrl.
Fix #93  
Add shallow test to render singUp dialog with and without policy agreement
* Yarn/npm/nodejs version:1.12.3/6.4.1/v8.14.1
* OS version:
* Chrome version:71.0.3578.98
> SignUp policy

- package.json
- webpack.common.js
- webpack.dev.js
- webpack.prod.js
- yarn.lock
Update Webpack-dev-server and linked dependencies.
Copy-webpack-plugin: 4.0.6
Html-webpack-plugin: ^3.2.0
Webpack: ^4.28.3
Webpack-cli: ^3.2.0
Webpack-dev-server: ^3.1.14
Webpack-merge: ^4.2.1
Test & lint have been lunched.
* Yarn/npm/nodejs version: 1.12.3/6.5.0/v8.10.0
* OS version:
* Chrome version:
> Update webpack-dev-server to fix vulnerability

- src/shared/containers/authenticate.jsx
- src/shared/sagas/index.js
Fix display signUp component when signUpValidation config key is not set.
Fix #109 
Yarn test & lint have been launched.
* Yarn/npm/nodejs version: v1.12.3/v6.5.0/v8.10.0
* OS version: macOS 10.14.2
* Chrome version: Google Chrome 71.0.3578.98
> Fix display signup

- package.json
- src/client/index.js
- src/shared/actions/api.js
- src/shared/actions/auth.js
- src/shared/actions/constants.js
- src/shared/actions/message.js
- src/shared/components/accountState.jsx
- src/shared/containers/admin/advanced.jsx
- src/shared/containers/admin/team.jsx
- src/shared/containers/app.jsx
- src/shared/containers/authenticate.jsx
- src/shared/containers/needAuth.jsx
- src/shared/containers/settingsManager.jsx
- src/shared/containers/userBox.jsx
- src/shared/middleware/signoutMiddleware.js
- src/shared/reducers/app.js
- src/shared/reducers/auth.js
- src/shared/reducers/message.js
- src/shared/sagas/api.js
- src/shared/sagas/auth.js
- src/shared/utils/queryParser.js
- tests/shared/middleware/signoutMiddleware.test.js
- tests/shared/reducers/message.test.js
- yarn.lock
Add new Dialog on Team container  …
Add AccountState component & all reducer to allow admin edit account status
Display info message when user signUp with validation mail/admin
Refactor Advanced container  …
Add from email textfield for smtp parameters
Remove getAdminParams from app & move it to Advanced container
Enhance not admin handling on Advanced container
Refactor Message handling  …
Refactor Authenticate component now u se only dialog
Add NeedAuth component to display on requiered auth pages
Allways show UserBox
Add QueryParser to parse query on front url linked to acount activation mail
cf Zoapp/backend#67
cf Zoapp/backend#29
linked to Opla/Opla#174
* Yarn/npm/nodejs version: v1.13.0/v5.6.0/v8.10.0
* OS version: macOS 10.14.2
* Chrome version: Google …
> Feature account state

- src/shared/middleware/signoutMiddleware.js
Clean up localStorage by sign out action when response error is 401.
Yarn tests & lint have been launched.
* Yarn/npm/nodejs version: v1.13.0/v5.6.0/v8.10.0
* OS version: macOS 10.14.3
* Chrome version: Google Chrome 72.0.3626.109
> Fix error linked to publish container

- package.json
- src/client/index.js
- src/shared/actions/auth.js
- src/shared/actions/constants.js
- src/shared/containers/authenticate.jsx
- src/shared/containers/lostPassword.jsx
- src/shared/reducers/auth.js
- src/shared/reducers/message.js
- src/shared/sagas/auth.js
- yarn.lock
Add new container lostPassword.
Add screen on /lost-password.
Add reducer for lost & change password.
FIx #94
Yarn lint & tests have been launched.
* Yarn/npm/nodejs version: v1.13.0/v5.6.0/v8.10.0
* OS version: macOS 10.14.3
* Chrome version: Google Chrome 72.0.3626.119
> Implement lost password feature
